### ISSUE TITLE
Build fails with com.sencha.exceptions.BasicException: GC overhead limit exceeded

### ISSUE THREAD

**Issue by cdrx** [rockmagic/sencha-cmd#3]
I work on an ExtJS app that is very large, and the build runs over the default memory limit. 

```
#8 51.85 [ERR] BUILD FAILED
#8 51.85 [ERR] com.sencha.exceptions.BasicException: GC overhead limit exceeded
#8 51.85 [ERR] 	at com.sencha.tools.compiler.a
#8 51.85 [ERR] st.BasicClosureConverter.convert(BasicClosureConverter.java:887)
```

Adding this line to the Dockerfile will fix it:

```
sed -i "s/^\-Xmx.*/\-Xmx2096m/" /opt/Sencha/Cmd/n.n.n.n/sencha.vmoptions
```

Are you open to a PR to add that? If so I'll raise it. 

I maintain a similar repo (https://github.com/cdrx/docker-sencha-cmd) but yours is better organised and there doesn't seem much point keeping both :)

**Comment by rockmagic** [comment]
@cdrx Thank you for the report. And yes, please submit the PR.

I'm not sure it's the best solution to hardcode `Xmx` option.
Did you try setting it with `_JAVA_OPTIONS` variable?

**Comment by cdrx** [comment]
I had no idea about that environment variable. It is even listed in the Sencha docs, don't know how I missed it.

It works perfectly, thank you.
